# Generated by Django 5.0 on 2025-12-12 19:21

import uuid

import django.db.models.deletion
import django_enum.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Transcription",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    django_enum.fields.EnumCharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("SUCCESS", "Success"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="TranscriptionData",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("output_language", models.CharField(default="en", max_length=20)),
                ("used_model", models.CharField(max_length=50)),
                ("generated_text", models.TextField()),
                (
                    "transcription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="results", to="transcriber.transcription"
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="transcription",
            constraint=models.CheckConstraint(
                check=models.Q(("status__in", ["PENDING", "PROCESSING", "SUCCESS", "FAILED"])),
                name="transcriber_Transcription_status_TranscriptionStatus",
            ),
        ),
    ]
