# Generated by Django 5.0 on 2025-12-13 21:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transcriber", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transcriptiondata",
            name="segments",
            field=models.JSONField(default=list),
        ),
    ]
